# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eRegulations
main_title: Help eRegulations
email: info@eregulations.com
description:
  en: Help for eRegulations
  es: Ayuda para eRegulations
baseurl: "" # the subpath of your site, e.g. /blog
url: "help.eregulations.org" # the base hostname & protocol for your site
github_username:  eregulations
port: 4002

index:
  en: '/'
  es: '/es'
  fr: '/fr'
  vn: '/vn'

# translations

translations:
  log:
    planned:
      en: "Planned on"
      es: "Planificado el"
      fr: "Prévu le"
      vn: "Planned on"

# Collections
collections:
  documentation:
    output: true
    title:
        en: 'Documentation'
        es: 'Documentación'
        fr: 'Documentation'
        vn: 'tài liệu'
    baseurl:
        en: '/documentation'
        es: '/es/documentacion'
        fr: '/fr/documentation'
        vn: '/vn/documentation'
  log:
    output: true
    title:
      en: 'Log'
      es: 'Log'
      fr: 'Log'
      vn: 'Log'
    baseurl:
      en: '/log'
      es: '/es/log'
      fr: '/fr/log'
      vn: '/vn/log'
  architecture:
    output: true
    title:
      en: 'Architecture'
      es: 'Arquitectura'
      fr: 'Architecture'
      vn: 'Architecture'
    baseurl:
      en: '/architecture'
      es: '/es/arquitectura'
      fr: '/fr/architecture'
      vn: '/vn/architecture'
  installation:
    output: true
    title:
      en: 'Installation'
      es: 'Instalación'
      fr: 'Installation'
      vn: 'Installation'
    baseurl:
      en: '/installation'
      es: '/es/instalacion'
      fr: '/fr/installation'
      vn: '/vn/installation'

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
